export const BASE_MODULE_LOADING = 'BASE_MODULE_LOADING'
export const BASE_MODULE_SET = 'BASE_MODULE_SET'
export const BASE_MODULE_RESET = 'BASE_MODULE_RESET'
export const BASE_MODULE_ERROR = 'BASE_MODULE_ERROR'
